# Generated by Django 4.0.5 on 2022-06-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miles',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='miles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miles', to='main_app.miles'),
        ),
    ]
