# Generated by Django 4.0.5 on 2022-06-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_miles_restaurant_restaurant_miles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miles',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='img',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='margarita',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
        migrations.AddField(
            model_name='miles',
            name='img',
            field=models.CharField(default='https://images.getbento.com/pCLkDroaRImKLsUfSYBT_logo_resized.png?w=600&fit=max&auto=compress,format&h=600', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miles',
            name='margarita',
            field=models.CharField(default='margarita', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miles',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
